# Generated by Django 3.1 on 2020-10-22 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('company', '0002_auto_20201022_2020'),
        ('topup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topuptransfer',
            name='receiver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topuptransfer',
            name='user_balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.usergasstationbalance'),
        ),
        migrations.AddField(
            model_name='topup',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.company'),
        ),
        migrations.AddField(
            model_name='topup',
            name='gas_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.gasstation'),
        ),
        migrations.AddField(
            model_name='topup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
