# Generated by Django 3.1 on 2020-11-01 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topup', '0002_auto_20201022_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuptransfer',
            name='sender_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topuptransfer',
            name='receiver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
