# Generated by Django 3.1 on 2020-11-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20201124_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_broadcast',
            field=models.BooleanField(default=False),
        ),
    ]
