# Generated by Django 3.1 on 2020-10-31 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchase_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='id_done',
            new_name='is_done',
        ),
    ]
