# Generated by Django 3.1 on 2020-11-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20201031_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='code_expiry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='number_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='qrcode_string',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
