# Generated by Django 3.1 on 2020-12-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20201101_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='direct_buy_with_card',
            field=models.BooleanField(default=True),
        ),
    ]
