# Generated by Django 3.1 on 2020-11-13 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201022_2020'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE FULLTEXT INDEX full_text_index_gasstation
                ON company_gasstation(name, address);
        """)
    ]
