# Generated by Django 3.1 on 2020-11-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20201113_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasstation',
            name='global_purchase_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
