# Generated by Django 3.1 on 2020-11-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE FULLTEXT INDEX full_text_index
                ON users_user(email, first_name, last_name);
        """)
    ]
