# Generated by Django 3.1 on 2020-11-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_full_text_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesid',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
